name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 4: Publish to GitHub Packages
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      #env:
     #   GITHUB_TOKEN: ${{ github.token }}
      
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build Docker image with multiple tags
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile \
          --tag "${{ secrets.DOCKER_USERNAME }}"/insure-me:latest \
        #  --tag "${{ secrets.DOCKER_USERNAME }}"/insure-me:${{ github.sha }}

    # Step 5: Push Docker image
    - name: Push Docker image
      run: |
        docker push "${{ secrets.DOCKER_USERNAME }}"/insure-me:latest
       # docker push "${{ secrets.DOCKER_USERNAME }}"/insure-me:${{ github.sha }}

    - name: run and validate image
      run: |
        docker run -itd -p 8091:8091 --hostname $(hostname -I | awk '{print $1}') ${{ secrets.DOCKER_USERNAME }}"/insure-me:latest
    
    - name: Curl container via runner IP
      run: |
        HOST_IP=$(hostname -I | awk '{print $1}')
        echo "Runner IP is: $HOST_IP"
        curl http://$HOST_IP:8091



        
